rode/rode-ui

.gitignore, .prettierignore, hooks/useTheme.js, package.json, utils/theme-utils.js
Suppresses this warning during a server-side render by calling `useEffect` instead of `useLayoutEffect`. This is one of the mitigations listed [here](https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85#option-1-convert-to-useeffect).
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
at ThemeProvider (webpack-internal:///./hooks/useTheme.js:38:74)
at MyApp (webpack-internal:///./pages/_app.js:46:3)
at AppContainer …
```
=> Suppress useLayoutEffect warning and show coverage

components/resources/ResourceBreadcrumbs.js, components/resources/ResourceOccurrences.js, components/resources/ResourceSearchBar.js, components/resources/ResourceSearchResult.js, hooks/useFetch.js, pages/api/resources.js, pages/index.js, pages/resources.js, pages/resources/[resourceUri].js, styles/modules/Resource.module.scss, styles/modules/ResourceSearch.module.scss, styles/modules/Resources.module.scss, test/components/resources/ResourceBreadcrumbs.spec.js, test/components/resources/ResourceOccurrences.spec.js, test/components/resources/ResourceSearchBar.spec.js, test/hooks/useFetch.spec.js, test/pages/api/resources.spec.js, test/pages/resources.spec.js, test/testing-utils/useFetchComponent.js, test/utils/resource-utils.spec.js, utils/resource-utils.js
Closes #14 and closes #15 
* Shows the resourceUri as the whole name, and version and type will show `N/A` if the resourceUri doesn't match an expected format
* Adds a "View all resources" link below the search to help someone get started. The text is not exactly true without the `.contains` filter being surfaced through Rode yet but we'll get there soon.
* Updates `useFetch` to take in the url and an object of query params
=> View all Resources & Fallback on resource uri

__mocks__/next/router.js, components/Button.js, components/ErrorBoundary.js, components/layout/PageLayout.js, components/resources/ResourceOccurrences.js, pages/404.js, pages/_error.js, pages/resources/[resourceUri].js, styles/modules/Buttons.module.scss, styles/modules/Errors.module.scss, styles/modules/Resource.module.scss, styles/modules/ResourceSearch.module.scss, test/ErrorBoundary.spec.js, test/components/Button.spec.js, test/components/resources/ResourceSearchBar.spec.js, test/pages/404.spec.js, test/pages/_error.spec.js, test/pages/resources.spec.js
* Adds error boundary to the whole app
* Adds custom error pages that show the same content as before, but now they follow the theme coloring so you won't get accidentally blinded
* Cut version off by adding ellipsis when it is too wide for your screen
* Fixes some icon button disabled styles
The error pages are super bare bones right now - if anyone has strong feelings about the error message we show let me know. Not sure if you guys like conversation messages like "Oops, something's not right here" or if people hate those. I was thinking it would be cool to get a graphic for the 404 page that looks like an anchor detached from a boat so we could stick with the Rode/anchor/ship theme.
=> Error Pages & Mobile improvements

pages/api/resources.js, test/pages/api/resources.spec.js
Dependent on [this PR in Rode](https://github.com/rode/rode/pull/32) to work.
=> Search for resources using .contains filter

components/occurrences/VulnerabilityOccurrenceDetails.js, styles/modules/OccurrenceDetails.module.scss, test/components/occurrences/VulnerabilityOccurrenceDetails.spec.js, test/testing-utils/mocks.js
Did not look at the documentation close enough to see what we have enums for severity, so now we should be showing all severity levels correctly
=> Handle critical and unspecified severities

jest-setup.js, providers/theme.js, test/providers/theme.spec.js
There's almost certainly a better way to do this, but this changes the initial theme value based on the user's theme preference.
Because of SSR there's a flash of unstyled content if the user has the dark theme preference. 
https://user-images.githubusercontent.com/9082799/113453477-aa50d380-93cb-11eb-9188-51eac63920a1.mov
=> Set default theme based on prefers-color-scheme

components/playground/EvaluationResult.js, pages/playground.js, pages/policies/[id].js, pages/resources/[resourceUri].js, styles/modules/Playground.module.scss, styles/modules/Policy.module.scss, styles/modules/Resource.module.scss, test/components/playground/EvaluationResult.spec.js, test/pages/playground.spec.js, test/pages/policies/[id].spec.js, test/pages/resources/[resourceUri].spec.js, test/testing-utils/mocks.js
Probably could have put this in the last PR but 🤷 it seemed like a natural break.
* Adds button to resource details and policy details to "Evaluate in Policy Playground" - auto populates the selected item
* Changes the evaluation failure to have a toggle-able code block showing the failed evaluation explanation
=> Evaluation Playground Part II

test/utils/resource-utils.spec.js, utils/resource-utils.js
As part of https://github.com/rode/rode/pull/48, I realized we should probably include the `groupId` as part of the resource name for Maven artifacts. Without it there's likely to be conflicts when artifacts have the same id. 
For an example of this happening, here's two packages with the same `artifactId`: [`org.eclipse.core:runtime`](https://mvnrepository.com/artifact/org.eclipse.core/runtime/3.10.0-v20140318-2214) and [`android.arch.persistence.room:runtime`](https://mvnrepository.com/artifact/android.arch.persistence.room/runtime/1.1.1).
=> Include groupId in resource name for Maven resources

components/occurrences/OccurrenceDetails.js, components/occurrences/SecureOccurrenceSection.js, components/playground/PlaygroundSearchResult.js, components/playground/ResourceSearchAndResults.js, components/resources/ResourceOccurrences.js, components/resources/ResourceSearchResult.js, components/shared/search/SearchResult.js, pages/api/occurrences.js, pages/playground.js, pages/resources/[resourceUri].js, styles/modules/OccurrenceDetails.module.scss, styles/modules/Occurrences.module.scss, styles/modules/Resource.module.scss, test/components/occurrences/OccurrenceDetails.spec.js, test/components/occurrences/SecureOccurrenceSection.spec.js, test/components/playground/PlaygroundSearchResult.spec.js, test/components/playground/ResourceSearchAndResults.spec.js, test/components/resources/ResourceSearchResult.spec.js, test/components/shared/search/SearchResult.spec.js, test/pages/api/occurrences.spec.js, test/pages/playground.spec.js, test/pages/resources/[resourceUri].spec.js, test/utils/occurrence-utils.spec.js, utils/occurrence-utils.js
Included in this PR
* Showing resource type in search results and policy playground
* Occurrence details takes up 2/3 of the screen, while the preview cards that you click take up 1/3 when you are viewing details of an occurrence
* Sticky Resource details header when viewing Resource details
* Add Critical severity to the breakdown list
* Show vulnerability breakdown on the occurrence preview of a vulnerability scan with vulnerabilities
* Adds large page size to the call to fetch occurrences so vulnerability scans will work as expected 
* Note: pagination is _not_ fully implemented yet in the UI, but this should be okay until pagination is fully worked out in grafeas-elasticsearch
---
_Coming in a follow-up PR_
* Download or copy JSON button
* Move the Show JSON button to the top of the …
=> Quick UI updates

.github/workflows/publish.yaml
Automagically compile a changelog history and create a github
release after a tag is published and an artifact is created.
#52
=> Automatically generate a changelog release on tag

pages/api/occurrences.js, pages/api/policies.js, pages/api/resources.js, test/pages/api/occurrences.spec.js, test/pages/api/policies.spec.js, test/pages/api/resources.spec.js
This changes the `/api/occurrences` endpoint to consume the `ListVersionedResourceOccurrences` endpoint, which takes a `resourceUri` instead of a filter.
It tries to match up related occurrences, which means that Git and artifact occurrence overviews should look the same now if there's a build occurrence linking them. 
docker image:
related Git commit:
I also made a small change to remove the quotes around any field names. The `filtering` package in `grafeas-elasticsearch` should handle those now (although quoting the fields still works).
=> Consume ListVersionedResourceOccurrences instead of ListOccurrences

.github/workflows/publish.yaml, release.json
Closes #71 
Adds config to populate the changelog. All of our PRs were getting classified as uncategorized, which doesn't seem to be rendered in the [default configuration](https://github.com/mikepenz/release-changelog-builder-action/blob/088993b64ceb224f5c7824ab510e8edb623aa875/src/configuration.ts#L41) (in the template `{{CHANGELOG}}` is the content of all categorized changes). 
<details>
<summary>Sample output</summary>
- Consume ListVersionedResourceOccurrences instead of ListOccurrences (#68)
- Syntax Highlighting, Example Hello World policy (#67)
- Pagination (#63)
- pin version of release-changelog-builder-action (#70)
ghcr.io/rode/ui:latest 
ghcr.io/rode/ui:v0.6.0-18-ge35e7aa
</details>
=> Populate release changelog

components/ExternalLink.js, components/Modal.js, components/occurrences/BuildOccurrenceDetails.js, components/occurrences/OccurrenceDetails.js, hooks/usePolicy.js, hooks/useSafeLayoutEffect.js, pages/api/utils/occurrence-utils.js, providers/theme.js, styles/constants.scss, styles/globals.scss, styles/modules/Header.module.scss, styles/modules/Inputs.module.scss, styles/modules/OccurrenceDetails.module.scss, test/components/ExternalLink.spec.js, test/components/occurrences/BuildOccurrenceDetails.spec.js, test/components/resources/ResourceSearchResult.spec.js, test/hooks/usePolicy.spec.js, test/hooks/useSafeLayoutEffect.spec.js, test/pages/api/utils/occurrence-utils.spec.js, test/providers/theme.spec.js
* Adds `useSafeLayoutEffect` hook that checks for server side rendering before using a client-only effect
* Shows "Source not available" or "Logs not available" when the field is not populated in a build occurrence
* Uses `git.uri` of the build occurrence to populate the source url
* Some styling updates for better accessibility/less box shadowing when focusing on inputs
=> Safe effects

components/playground/SelectedPolicy.js, components/playground/SelectedResource.js, cypress/integration/Resource/resource.js, pages/api/utils/occurrence-utils.js, styles/modules/Playground.module.scss, test/components/playground/SelectedResource.spec.js, test/pages/api/utils/occurrence-utils.spec.js, test/pages/playground.spec.js
* Shows the occurrence data for a resource in the policy playground, similar to showing rego code for the selected policy
* Sets height of occurrence data and rego code in playground, can be expanded vertically
* Fixes a failing cypress test
=> Show occurrence data in policy playground

.github/workflows/publish.yaml
The latest release opened https://github.com/rode/charts/pull/57, which had a PR title indicating it was bumping Rode and not Rode UI.
=> Fix chart promotion message

components/playground/EvaluationResult.js, components/playground/ResourceSelectionDrawer.js, components/playground/SelectedPolicy.js, components/playground/SelectedResource.js, styles/modules/Playground.module.scss, test/components/playground/SelectedPolicy.spec.js, test/components/playground/SelectedResource.spec.js
* Adds back policy name, resource name and version when you have selected a policy/resource for evaluation.
* Fixes some styling issues with overflowing code content and evaluation results
=> Show Selected Policy & Resource Details in playground

cypress/fixtures/resources.json, pages/api/utils/occurrence-utils.js, test/pages/api/utils/occurrence-utils.spec.js, test/testing-utils/mocks.js
Closes #93 
Groups vulnerability scans by the `noteName` instead of the `createTime`
=> Group scans by the note name

components/LabelWithValue.js, components/occurrences/BuildOccurrenceSection.js, components/occurrences/SecureOccurrenceSection.js, components/occurrences/VulnerabilityOccurrenceDetails.js, pages/api/occurrences.js, pages/api/utils/occurrence-utils.js, pages/resources/[resourceUri].js, styles/modules/OccurrenceDetails.module.scss, test/components/LabelWithValue.spec.js, test/components/occurrences/SecureOccurrenceSection.spec.js, test/components/occurrences/VulnerabilityOccurrenceDetails.spec.js, test/pages/api/occurrences.spec.js, test/pages/api/utils/occurrence-utils.spec.js
* Pulls related notes when fetching occurrences and uses those notes to display better information about the vulnerability scan.  
* Also pulls any finished scan, not just the successful ones, to correctly show sonar scans
* Fixes issue with nested p tags causing a react dev warning
Another PR will add note information to the other occurrence types once the other collectors are producing notes that can be consumed.
Closes #104 , Closes #107
=> Consume notes for scans

components/Drawer.js, components/layout/Header.js, components/playground/ResourceVersionSearchAndResults.js, components/resources/ChangeVersionDrawer.js, pages/index.js, pages/resources.js, styles/modules/Drawer.module.scss, test/components/Drawer.spec.js, test/components/layout/Header.spec.js, test/components/playground/PolicySearchAndResults.spec.js, test/components/resources/ChangeVersionDrawer.spec.js, test/components/resources/ResourceSelectionDrawer.spec.js, test/pages/resources/[resourceUri].spec.js, test/utils/resource-utils.spec.js, utils/resource-utils.js
* Adds version searching to the change version drawer when viewing a resource
* Change how event listeners are added/removed - sometimes my long running environment would have too many listeners and this should fix that.
* Update wording on resource search to remove references about searching by the version. This may be [added to rode](https://github.com/rode/rode/issues/91) later, but I'm removing for now to avoid confusion.
=> Version Searching, small UI and performance enhancements

components/policies/PolicyForm.js, pages/api/occurrences.js, pages/api/policies.js, pages/api/policies/[id].js, pages/api/policies/[id]/attest.js, pages/api/policies/validate.js, pages/api/resource-versions.js, pages/api/resources.js, pages/api/utils/api-utils.js, pages/api/utils/policy-utils.js, pages/playground.js, pages/policies/[id].js, pages/policies/new.js, test/components/policies/PolicyForm.spec.js, test/pages/api/occurrences.spec.js, test/pages/api/policies.spec.js, test/pages/api/policies/[id].spec.js, test/pages/api/policies/[id]/attest.spec.js, test/pages/api/policies/validate.spec.js, test/pages/api/resource-versions.spec.js, test/pages/api/resources.spec.js, test/pages/api/utils/api-utils.spec.js, test/pages/api/utils/policy-utils.spec.js, test/pages/playground.spec.js, test/pages/policies/[id]/edit.spec.js, test/pages/policies/new.spec.js
Closes #112 
* consumes the updated policy model
* adds api call helpers to handle some of the formatting needed to send data
* adds mappers to isolate changes needed to update the policy model
* removes some unneeded tests and set-up
This is dependent on a new release of Rode. As of [v0.9.2](https://github.com/rode/rode/releases/tag/v0.9.2) the policy model is not yet updated for these changes.
=> Policy version updates

components/playground/ResourceSearchAndResults.js, components/playground/ResourceSelectionDrawer.js, components/playground/ResourceVersionSearchAndResults.js, components/playground/SelectedResource.js, pages/api/resource-versions.js, pages/playground.js, test/components/playground/ResourceSearchAndResults.spec.js, test/components/playground/ResourceVersionSearchAndResults.spec.js, test/components/playground/SelectedResource.spec.js, test/components/resources/ResourceSelectionDrawer.spec.js, test/pages/api/resource-versions.spec.js
Just renaming some variables to remove the idea of a `generic-resource` from the code base.
Closes #115
=> Remove generic resource from code

components/Button.js, components/layout/Header.js, components/layout/PageHeader.js, components/policies/PolicyForm.js, hooks/useFormValidation.js, pages/api/policies.js, pages/api/policy-groups.js, pages/api/resource-versions.js, pages/api/resources.js, pages/api/utils/api-utils.js, pages/playground.js, pages/policy-groups.js, pages/policy-groups/new.js, schemas/policy-group-form.js, styles/modules/Header.module.scss, styles/modules/Playground.module.scss, styles/modules/Policy.module.scss, styles/modules/PolicyGroupDashboard.module.scss, styles/modules/PolicyGroupForm.module.scss, test/components/layout/Header.spec.js, test/pages/api/policies.spec.js, test/pages/api/policy-groups.spec.js, test/pages/api/resource-versions.spec.js, test/pages/api/resources.spec.js, test/pages/api/utils/api-utils.spec.js, test/pages/policy-groups.spec.js, test/pages/policy-groups/new.spec.js
* Adds screens and functionality for creating new policy group and viewing all groups in a dashboard
* Refactors some of the pagination parameter building on the api
* Refactors some styles that were duplicated across multiple page headers
Closes #117
=> Policy groups: create new and dashboard

components/policy-groups/PolicyGroupForm.js, cypress/integration/Policy.feature, styles/modules/PolicyGroupForm.module.scss, test/pages/policy-groups/[name]/edit.spec.js
Closes #121 
Super simple delete functionality. Since there's no assignments yet, there is no prompt to confirm your choice to delete.
Once policy assignment is happening in the UI, I'll update this flow to include a confirmation and notice that there are X policies assigned to the policy group.
=> Delete Policy Group

components/Text.js, components/policies/PolicyHistory.js, components/resources/PolicyEvaluationDetails.js, components/resources/ResourceEvaluation.js, pages/policies/[id].js, styles/modules/Policy.module.scss, styles/modules/PolicyHistory.module.scss, test/components/policies/PolicyHistory.spec.js, test/components/resources/PolicyEvaluationDetails.spec.js, test/components/resources/ResourceEvaluation.spec.js, test/pages/policies/[id].spec.js
per Robert, closes #150 
* Viewing a policy now shows the current version you are viewing, as well as the latest version of the policy
* When coming from search, these will always match because we show the latest version of the policy
* When coming from resource evaluation history, these may not match depending on the policy group assignment
* Viewing policy history, you can now click on the version to toggle the rego content (similar to the vulnerability cards on a resource)
* Resource Evaluation History now links to the policy groups and policy at the evaluated version.
=> Usability Requests

Dockerfile
I noticed our UI images were a bit large and it seems like the main issue is the yarn cache. Switching to a multi-stage build ensures the cache doesn't end up in the final image for a ~50% size reduction. Likely some additional improvements could be made, but I think this is a good first step. 
```
$ docker images rode-ui
REPOSITORY   TAG        IMAGE ID       CREATED              SIZE
rode-ui      local-v2   8e9a87a7f602   About a minute ago   189MB
rode-ui      local      01433c3b8182   15 minutes ago       420MB
```
=> Use multi-stage build

pages/api/policy-groups/[name]/assignments.js, test/pages/api/policy-groups/[name]/assignments.spec.js
apparently we were not sending a request body when creating policy assignments.  looking through the history, we never did, but I swear I've done this before and have seen it working in the past.
=> add missing request body to policy assignment POST

components/occurrences/SecureOccurrenceSection.js, components/occurrences/VulnerabilityOccurrenceDetails.js, pages/api/utils/occurrence-utils.js, test/components/occurrences/SecureOccurrenceSection.spec.js, test/components/occurrences/VulnerabilityOccurrenceDetails.spec.js, test/pages/api/utils/occurrence-utils.spec.js, test/testing-utils/mocks.js
=> display message in vulnerability occurrence summary when discovery analysis failed

.github/workflows/verify.yaml, server/middleware.mjs, test/server/middleware.spec.js
If the request to refresh the access token fails, we try to redirect to login. However, this doesn't drop the existing session cookies so the request gets stuck in loop trying and failing to refresh the token, then redirecting to `/login`. 
This PR changes the middleware to end the session, but doesn't try to reinitiate a login. I tested this by lowering the access token lifespan to 1 minute, invalidating the session in Keycloak, and waiting for a refresh to happen. 
Likely there could be some better UX here, see #167 and likely #165 would be helpful.
=> Drop session cookies after refresh failure
